constants:
  sample_rate: &sample_rate 16000
  slice: &slice 1
  epo: &epo 3000

exp:
  exp_name: JustMamba_ONETOKEN

# assert self.d_inner % self.headdim == 0
# self.d_inner = self.expand * self.d_model
# causal conv 1d  stride rule -> -> d_model * expand / headdim = multiple of 8

# Network config
# RUN 1 -> OneToken 16khz 1 3000
# RUN 2 -> linear 
audionet:
  audionet_name: JustMambaTF
  audionet_config:
    n_layers: 1 #6
    dim: 4000
    length: 1
    headdim: 128
    expand: 4
    swap_DL: True
    bidirectional: False
    eps: 1.0e-5
    sample_rate: *sample_rate

loss:
  train:
    loss_func: MultiLoss
    config:
      sample_rate: *sample_rate
      k_mel: 1
      k_snr: 0
      n_mels: 600
      n_fft: 8192
  val:
    loss_func: MultiLoss
    config:
      sample_rate: *sample_rate
      k_mel: 1
      k_snr: 0
      n_mels: 600
      n_fft: 8192



training:
  system: AudioLightningModule
  gpus: [0]
  parallel: ddp
  epochs: *epo
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 500
    verbose: true
  SpeedAug: False

# Optim config
optimizer:
  optim_name: adam
  lr: 0.00001
  weight_decay: 0

# Sche config
scheduler:
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 200
    factor: 0.8

# Data config
datamodule:
  data_name: starNetDataModule
  data_config:
    train_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/train
    valid_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/val
    test_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/test
    num_chan: 1
    sample_rate: *sample_rate
    segment: *slice
    source_timbre: 2
    target_timbre: 3
    normalize_audio: false
    batch_size: 1
    num_workers: 8
    pin_memory: true
    persistent_workers: false
