exp:
  exp_name: JustMamba_Mel_MAE_STFT


# Network config
audionet:
  audionet_name: JustMambaTF
  audionet_config:
    n_chan: 1
    n_layers: 8 #6
    emb_dim: 1 #16
    emb_ks: 64 #8
    eps: 1.0e-5
    sample_rate: 32000
# Loss config
  #  loss_func: MelSpectrogramLoss
  #  config:
  #    stereo: False
  #    sample_rate: 8000
loss:
  train:
    loss_func: MelMAESpectrogramLoss
    config:
      sample_rate: 32000
  val:
    loss_func: MelMAESpectrogramLoss
    config:
      sample_rate: 32000



training:
  system: AudioLightningModule
  gpus: [0]
  parallel: ddp
  epochs: 1000
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 500
    verbose: true
  SpeedAug: False

# Optim config
optimizer:
  optim_name: adam
  lr: 0.000001
  weight_decay: 0

# Sche config
scheduler:
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 200
    factor: 0.8

# Data config
datamodule:
  data_name: starNetDataModule
  data_config:
    train_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/train
    valid_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/val
    test_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/test
    num_chan: 1
    sample_rate: 32000
    segment: 2
    source_timbre: 2
    target_timbre: 3
    normalize_audio: false
    batch_size: 1
    num_workers: 8
    pin_memory: true
    persistent_workers: false
