
# Network config
audionet:
  audionet_name: MambaTF
  audionet_config:
    input_dim: 64
    n_fft: 256
    stride: 64
    window: hann
    n_chan: 1
    n_layers: 3 #6
    lstm_hidden_units: 256
    attn_n_head: 4 #4
    attn_approx_qk_dim: 512
    emb_dim: 16
    emb_ks: 8
    emb_hs: 1
    activation: prelu
    eps: 1.0e-5
    use_builtin_complex: False

# Loss config
loss:
  train:
    loss_func: MAELoss
    config:

  val:
    loss_func: MAELoss
    config:


training:
  system: AudioLightningModule
  gpus: [0]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 20
    verbose: true
  SpeedAug: False

# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler:
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 10
    factor: 0.5

# Data config
datamodule:
  data_name: starNetDataModule
  data_config:
    train_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/train
    valid_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/val
    test_dir: /nas/home/gfraticcioli/datasets/starnet/metadatas/test
    num_chan: 1
    sample_rate: 16000
    segment: 1
    source_timbre: 1
    target_timbre: 4
    normalize_audio: false
    batch_size: 1
    num_workers: 8
    pin_memory: true
    persistent_workers: false

exp:
  exp_name: MambaTF-StarNet
